### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by cgmccanna** [cgmccanna/driving-game-1222#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a basic HTML skeleton
- [x] Create new CSS stylesheet and use CSS to set the body elements background color to green
- [x] Add an `img` element to the body with a `src` attribute with a value of a relative path to the car icon
- [x] Set the size of the car icon to fit correctly in the top left corner of the page

**Comment by cgmccanna** [comment]
![user-can-see-car](https://user-images.githubusercontent.com/74582871/207224198-2b8c4702-639d-4e69-8803-70d6139ba3bc.png)
