### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by cgmccanna** [cgmccanna/driving-game-1222#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create an object named 'car' in main.js with a property to hold the cars direction
- [x] Create separate CSS classes which rotate the car each of the 4 directions
- [x] Query the dom for the car image element and assign it to $car
- [x] Add an event listener for the keydown event and....
     - [x] Use if and else statements to set the car objects direction property to the direction of the key that was pressed
     - [x] set the class of the car img element to the value of the car objects direction
- [x] use css transitions to ensure car image rotates smoothly
