### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by cgmccanna** [cgmccanna/driving-game-1222#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] give the car object a location to hold x and y coordinates of the car on the page
- [x] set the positioning of the car to 'absolute'
- [x] create a function called 'start' and...
     - [x] use if and else if statements to handle both possible starting direction properties of the car
     - [x] within each if/if else statement, increase the value of the car's x or y property by 7
     - [x] set the style of the $car's correlating box offset direction to equal the x or y value of the car object
- [x] add an event listener on the document for the keydown event and...
     - [x] if the pressed key was 'Space', set an Interval to call the 'start' function every 16 milliseconds
- [x] clean up any bugs/issues, console logs, or commented out code
