### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by cgmccanna** [cgmccanna/driving-game-1222#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] add a property called 'started' to the car object to hold a boolean value indicating if the car is started
- [x] add a condition to the keydown event listener function to only begin the setinterval function to start the car if the 'started' property is false
- [x] add a condition to the above function to clear the interval if the cars 'started' property is true
